display:
  default:
    display_options:
      filters:
        group_roles_target_id_2:
          id: group_roles_target_id_2
          table: group_content__group_roles
          field: group_roles_target_id
          relationship: group_content
          group_type: group
          admin_label: ''
          operator: '='
          value: public_group-group_manager
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin_id: string
