display:
  default:
    display_options:
      arguments:
        gid:
          specify_validation: true
          validate:
            type: entity:group
          validate_options:
            access: ''
            bundles:
              closed_group: closed_group
              open_group: open_group
              public_group: public_group
            multiple: false
            operation: view
      filters:
        type:
          value:
            closed_group-group_node-event: closed_group-group_node-event
            open_group-group_node-event: open_group-group_node-event
            public_group-group_node-event: public_group-group_node-event
